### ISSUE TITLE
Fails when I add it in .net core project

### ISSUE THREAD

**Issue by carmonac** [naudio/NAudio.WaveFormRenderer#12]
I add this reference through nugget package to .net core project in macOS and it says that the target has to be Windows

**Comment by markheath** [comment]
The top-level NAudio package includes a whole bunch of components that aren't cross-platform (they use Windows specific APIs). You could just try referencing NAudio.Core if that contains what you need.

**Comment by markheath** [comment]
Sorry, thought this query was about NAudio, not WaveFormRenderer. It's because it uses AudioFileReader. I could change it so you pass in an `ISampleProvider` and length, but that would be a breaking change so a new major version would be needed

**Comment by markheath** [comment]
try v2 - may meet your needs
