### ISSUE TITLE
Render Waveform for Region of Audio File

### ISSUE THREAD

**Issue by psideas** [naudio/NAudio.WaveFormRenderer#3]
Is there a way to render a waveform based upon a region of an audio file (denoted by a startOffset and endOffset) as opposed to the entire audio file? If so, could you provide the code modifications?

**Comment by markheath** [comment]
it uses an `AudioFileReader`, so you can jump in that file with `CurrentTime` and you can limit the duration with the `Take` extension method.


    reader.CurrentTime = TimeSpan.FromSeconds(30);
    peakProvider.Init(reader.Take(TimeSpan.FromSeconds(20)), samplesPerPixel * stepSize);

**Comment by nikitoSha** [comment]
> reader.Take

No such method.

**Comment by nikitoSha** [comment]
> 
> 
> it uses an `AudioFileReader`, so you can jump in that file with `CurrentTime` and you can limit the duration with the `Take` extension method.
> 
> ```
> reader.CurrentTime = TimeSpan.FromSeconds(30);
> peakProvider.Init(reader.Take(TimeSpan.FromSeconds(20)), samplesPerPixel * stepSize);
> ```

Hi. Not working. "Init" creates new reader with default startTime!


                 AudioFileReader reader = new AudioFileReader(audioFilePath);

                // 1. Конфигурация провайдеров
                //OffsetSampleProvider offsetSampleProvider = new OffsetSampleProvider(reader);

                MaxPeakProvider maxPeakProvider = new MaxPeakProvider();
                RmsPeakProvider rmsPeakProvider = new RmsPeakProvider(200);
                SamplingPeakProvider samplingPeakProvider = new SamplingPeakProvider(200);
                AveragePeakProvider averagePeakProvider = new AveragePeakProvider(4);

                // 2. Конфигурация стиля шкалы
                StandardWaveFormRendererSettings myRendererSettings = new StandardWaveFormRendererSettings();
                myRendererSettings.Width = waveFormWidth;
                myRendererSettings.TopHeight = formTopHeight;
                myRendererSettings.BottomHeight = formBottomHeight;

                // 3. Формирование изображения со шкалой
                WaveFormRenderer renderer = new WaveFormRenderer();

                reader.CurrentTime = TimeSpan.FromSeconds(startMediaSecond);                
                averagePeakProvider.Init(reader.Take(TimeSpan.FromSeconds(endMediaSecond - startMediaSecond)), 200);                

                image = renderer.Render(audioFilePath, averagePeakProvider, myRendererSettings); 
```

**Comment by nikitoSha** [comment]
I append one function to this lib. Why you don't do it yet - I don'r understand

**Comment by nikitoSha** [comment]
```
        public Image RenderWithTake(string selectedFile, IPeakProvider peakProvider, 
            WaveFormRendererSettings settings, int startFromSeconds, int duration )
        {
            using (var reader = new AudioFileReader(selectedFile))
            {
                reader.CurrentTime = TimeSpan.FromSeconds(startFromSeconds);

                int bytesPerSample = (reader.WaveFormat.BitsPerSample / 8);
                var samples = reader.Length / (bytesPerSample);
                var samplesPerPixel = (int)(samples / settings.Width);
                var stepSize = settings.PixelsPerPeak + settings.SpacerPixels;
                peakProvider.Init(reader.Take(TimeSpan.FromSeconds(duration)), samplesPerPixel * stepSize);
                return Render(peakProvider, settings);
            }
        }
```

**Comment by nikitoSha** [comment]
Wrong draw:
1. start from 0 second to normal 1 min 59 sec
2. start from not 0 second. No Fill.

![foo_0](https://user-images.githubusercontent.com/15741303/92369251-f8964080-f122-11ea-8700-4c3b0413e790.png)
![foo_1](https://user-images.githubusercontent.com/15741303/92369257-f9c76d80-f122-11ea-90c2-beda49d12b7c.png)

**Comment by nikitoSha** [comment]
Okay. This:
`peakProvider.Init(reader.Take(TimeSpan.FromSeconds(duration)), samplesPerPixel * stepSize);`
Contains empty peaks in the end. That's why it draws empty.
How to remove this empty peaks? "Init" creates peakProvider with full length

**Comment by Jando132456** [comment]
![image](https://user-images.githubusercontent.com/110132865/202835605-4f4a6e34-c4db-4513-bcad-fa5b37572128.png)
error me sale al usar StandardWaveFormRendererSettings(); error ayuda por favor

**Comment by LunevNF** [comment]
Which error? Show the full error info from IDE?
